name: "Build & publish mqtt2pulseaudio release"

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19.1'
      - run: GOOS=linux GOARCH=amd64 go build -ldflags="-X main.VERSION=${GITHUB_REF##*/} -X main.COMMIT=${GITHUB_SHA}" -o mqtt2pulseaudio-${GITHUB_REF##*/}-linux-x86_64 .
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "mqtt2pulseaudio-*-*-*"
          token: ${{ secrets.GITHUB_TOKEN }}
